project:
  type: website
  output-dir: docs

website:
  title: "SIVCA"
  navbar:
    left:
      - text: "Acerca de"
        href: about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

filters:
  - shinylive
  
lang: es

editor: visual

